# Generated by Django 4.2.6 on 2023-11-19 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=60, unique=True, verbose_name='Kraj powstania gry')),
            ],
        ),
        migrations.CreateModel(
            name='GameStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_average', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3)),
                ('vote_count', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer', models.CharField(max_length=35, unique=True, verbose_name='Producent (główny) gry')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('cycle', models.CharField(blank=True, max_length=30)),
                ('release_date', models.DateField(blank=True)),
                ('depiction', models.TextField(blank=True)),
                ('country', models.ForeignKey(blank=True, default='', on_delete=models.SET(''), to='games.country')),
                ('genres', models.ManyToManyField(to='games.genre')),
                ('producer', models.ForeignKey(blank=True, default='', on_delete=models.SET(''), to='games.producer')),
                ('statistics', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='games.gamestatistics')),
            ],
        ),
    ]
