# Generated by Django 4.2.6 on 2023-11-09 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=60, verbose_name='Kraj powstania gry')),
            ],
        ),
        migrations.CreateModel(
            name='GamesGenres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=1000)),
                ('genre_id', models.CharField(max_length=3)),
                ('genre', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GameStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_average', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('vote_count', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer', models.CharField(max_length=35, verbose_name='Producent (główny) gry')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('cycle', models.CharField(max_length=30, null=True)),
                ('release_date', models.DateField(null=True)),
                ('depiction', models.TextField(null=True)),
                ('genres', models.TextField(null=True)),
                ('country', models.ForeignKey(default='null', null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.country')),
                ('producer', models.ForeignKey(default='null', null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.producer')),
                ('statistics', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.gamestatistics')),
            ],
        ),
    ]
